### ISSUE TITLE
Mobile - gallery page: Some albums are centered some are not.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hearth-House#103]
iPad, iTouch 
![image](https://cloud.githubusercontent.com/assets/11186313/7976463/ed2634c8-0aad-11e5-99fa-8c3d257d6f4b.png)

**Comment by roseliesromeo** [comment]
Not fixed in iPad air

**Comment by genesiscebudigital** [comment]
pls provide screenshot

**Comment by roseliesromeo** [comment]
Still not fixed
![image](https://cloud.githubusercontent.com/assets/11186313/8101454/dfa27054-1049-11e5-9cc8-58c4d5b6aa86.png)
