### ISSUE TITLE
Banner Section:  The banner title display seems not consistent with the other browser 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Hearth-House#16]
![banner_01](https://cloud.githubusercontent.com/assets/11186386/7717734/ca1d1914-fed8-11e4-9898-2f994de2dab8.jpg)

**Comment by roseliesromeo** [comment]
Not fixed in IE8
![image](https://cloud.githubusercontent.com/assets/11186313/8101076/264827c8-1046-11e5-846a-5ff93dcaaa5f.png)
