### ISSUE TITLE
Lead Ins section :  Where we can edit and update the title content  on (we are perths.... and We stock a large.... ) ?

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Hearth-House#18]
![lead ins_02](https://cloud.githubusercontent.com/assets/11186386/7718318/2f05ced6-fee1-11e4-97db-3739edb9ed8e.jpg)

**Comment by roseliesromeo** [comment]
Not fixed for "We Stock A Large Range of Trusted Brands" section.
And how about for "see what we can do for you" text?

**Comment by roseliesromeo** [comment]
Not fixed for the "see what you can do for you" text.
