### ISSUE TITLE
Home page: Enhancement:  Better adjust the button layout something bigger and looks like the design specs.

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Hearth-House#25]
![home_05](https://cloud.githubusercontent.com/assets/11186386/7719624/b7856c44-fef5-11e4-8ab2-4e99fe644526.jpg)

**Comment by roseliesromeo** [comment]
Button size should be at least 195px x 50px

**Comment by roseliesromeo** [comment]
Get a Quote Today and the View buttons doesn't match the design.
![image](https://cloud.githubusercontent.com/assets/11186313/8028730/d6c1b136-0de5-11e5-9097-8b2e453921b8.png)
