### ISSUE TITLE
Header Page:  Header layout on IE 7 not match from design specs 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Hearth-House#39]
![header page_02](https://cloud.githubusercontent.com/assets/11186386/7720288/2de4f3b6-fefe-11e4-9c07-54a1148bfffc.jpg)

**Comment by roseliesromeo** [comment]
Bottom of the menu bar and the logo are not aligned in IE, all browser mode.
Right edge of the Request a quote button is not aligned with the header section container.
![image](https://cloud.githubusercontent.com/assets/11186313/7975967/6b751f58-0aa7-11e5-976e-15b0ed8a88c9.png)

**Comment by roseliesromeo** [comment]
Right edge of the Request a quote button is still not aligned with the header section container in IE7 only.
