### ISSUE TITLE
Privacy Policy: IE 7 only:  Missing list item numbers on privacy content that leads to inconsistency from other browser

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Hearth-House#6]
![privacy_01](https://cloud.githubusercontent.com/assets/11186386/7699380/13030a9c-fe4a-11e4-85c1-5a2bf4c2daa0.jpg)

**Comment by roseliesromeo** [comment]
Changed from numbered list to bullet list for all browsers.
