### ISSUE TITLE
Product single page: View Gallery button isn't linked to Gallery page by category but will show/hide thumbnails instead.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hearth-House#67]

**Comment by roseliesromeo** [comment]
It will still show thumbnails before directing to the gallery page.

**Comment by roseliesromeo** [comment]
Shouldn't View Gallery button link to Gallery page instead of showing/hiding the gallery thumbnails?
Please verify the correct behavior.

**Comment by genesiscebudigital** [comment]
the correct behavior for gallery is show /hide :D
