### ISSUE TITLE
Mobile - Header section: Bottom of the logo and the menu bar is not aligned.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hearth-House#68]
iPad

![image](https://cloud.githubusercontent.com/assets/11186313/7740810/900dfc08-ffa9-11e4-8b1b-9c2cb928d43d.png)

**Comment by roseliesromeo** [comment]
No change made.

**Comment by genesiscebudigital** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11186352/8053935/7b3a7554-0ec7-11e5-8f4f-f4ca21872047.png)

it is ok in my end . ,clear cache

**Comment by roseliesromeo** [comment]
Still not fixed
![image](https://cloud.githubusercontent.com/assets/11186313/8101510/72a5cf90-104a-11e5-9510-c6eb93bf46ed.png)
