### ISSUE TITLE
Search results page:  It will only list up to ten items instead of all related results.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hearth-House#70]

**Comment by arielcebudigital** [comment]
It display all the result list, it paginate after 10 list, since you want to display all list i change the admin setting to 100

**Comment by roseliesromeo** [comment]
That's not what I meant.

The last time I check, it will display 10 related results only.  The previous button will display the previous search results and the first time I tried to search something, there is already previous link.
