### ISSUE TITLE
Our team: W3C; 3 Errors, 5 warning(s)

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hearth-House#81]
http://validator.w3.org/check?verbose=1&uri=http://hearthouse.stage.titanweb.com.au/our-team/

**Comment by arielcebudigital** [comment]
Same Error of About us page: W3C; 3 Errors, 5 warning(s) #80 
https://github.com/titan-cebu/Hearth-House/issues/80 - (the issue is on header area)
